export const users = [
    {
        id: 1,
        fullName: "Nguyễn Văn A",
        username: "nguyenvana",
        email: "a.nguyen@example.com",
        password: "88888888",
        status: "Đang hoạt động",
        active: true,
        role: "Quản trị viên",
    },
    {
        id: 2,
        fullName: "Trần Thị B",
        username: "tranthib",
        email: "b.tran@example.com",
        password: "123abc",
        status: "Tạm khóa",
        active: false,
        role: "Người dùng",
    },
    {
        id: 3,
        fullName: "Lê Văn C",
        username: "levanc",
        email: "c.le@example.com",
        password: "123456",
        status: "Đang hoạt động",
        active: true,
        role: "Biên tập viên",
    },
    {
        id: 4,
        fullName: "Trần Thị B",
        username: "tranthib",
        email: "b.tran@example.com",
        password: "123abc",
        status: "Tạm khóa",
        active: false,
        role: "Người dùng",
    },
    {
        id: 5,
        fullName: "Lê Văn C",
        username: "levanc",
        email: "c.le@example.com",
        password: "123456",
        status: "Đang hoạt động",
        active: true,
        role: "Biên tập viên",
    },
];